### ISSUE TITLE
Diff between commands and script commands

### ISSUE THREAD

**Issue by ghost** [mtkirby/audisp-simplify#2]
Hi!
Wonderful job ;)
I have a question about log all the commands ... do you think it's possible to log only the commands executed by a human in the shell and not the commands executed by a script (even if it's the human who run the script ...) ?

**Comment by johnebgood** [comment]
I would think that in the perl script you could check to see if a user is logged in to the corresponding tty where the command is executed, is this what you're looking for?

**Comment by ghost** [comment]
Yep I was thinking about that a few minutes ago.
But the point is the script is a logon script, executed when the user comes on the server ... and in fact it's executed by the user. So it's the same tty, same ppid, etc ...

**Comment by ghost** [comment]
Basically, it would be awesome if auditd could not track the commands executed in a script ... maybe I'm dreaming but it would be what I need to do ;-)

**Comment by mtkirby** [comment]
Yup, you are correct.  Unfortunately, that is not something we can do with
the audit system.
I've read that some admins use Bash's PROMPT_COMMAND variable to send shell
history to a syslog server in real-time, but that can be easily defeated if
the user wishes to hide.
