### ISSUE TITLE
last audit messages absent in audisp-simplify

### ISSUE THREAD

**Issue by meshkov** [mtkirby/audisp-simplify#3]
Hello!
The problem is that the latest event from my audit file does not appear in audisp-simplify. New events never appear in audit-simplify until the next ones come. Only then can I see the last event but one. 
Here is an example of what's happening.
audit.rules
`# auditctl -l
-w /usr/sbin/useradd -p wa -k useradd
`
I try to create 2 users `useradd test1` and `uaseradd test2`. After that my audit.log contains the following information about these events.
`
type=USER_AUTH msg=audit(1499773986.003:28912): pid=20885 uid=0 auid=0 ses=1254  msg='op=PAM:authentication acct="root" exe="/usr/sbin/useradd" hostname=? addr=? terminal=pts/1 res=success'
type=USER_ACCT msg=audit(1499773986.003:28913): pid=20885 uid=0 auid=0 ses=1254  msg='op=PAM:accounting acct="root" exe="/usr/sbin/useradd" hostname=? addr=? terminal=pts/1 res=success'
type=ADD_USER msg=audit(1499773986.055:28914): pid=20885 uid=0 auid=0 ses=1254  msg='op=adding user id=1003 exe="/usr/sbin/useradd" hostname=? addr=? terminal=pts/1 res=success'
type=USER_AUTH msg=audit(1499774090.411:28915): pid=21042 uid=0 auid=0 ses=1254  msg='op=PAM:authentication acct="root" exe="/usr/sbin/useradd" hostname=? addr=? terminal=pts/1 res=success'
type=USER_ACCT msg=audit(1499774090.411:28916): pid=21042 uid=0 auid=0 ses=1254  msg='op=PAM:accounting acct="root" exe="/usr/sbin/useradd" hostname=? addr=? terminal=pts/1 res=success'
type=ADD_USER msg=audit(1499774090.471:28917): pid=21042 uid=0 auid=0 ses=1254  msg='op=adding user id=1004 exe="/usr/sbin/useradd" hostname=? addr=? terminal=pts/1 res=success'
`
But in audisp-simplify the only information that appears is the information about creating the first user (test1):
`
acct="root" auditid="28912" auid="0" auid_user="root" date="2017-07-11" exe="/usr/sbin/useradd" node="zabbix" op="PAM:authentication" pid="20885" res="success" ses="1254" terminal="pts/1" time="14:53:06.003" timezone="+0300" types="USER_AUTH" uid="0" uid_user="root"
acct="root" auditid="28913" auid="0" auid_user="root" date="2017-07-11" exe="/usr/sbin/useradd" node="zabbix" op="PAM:accounting" pid="20885" res="success" ses="1254" terminal="pts/1" time="14:53:06.003" timezone="+0300" types="USER_ACCT" uid="0" uid_user="root"
auditid="28914" auid="0" auid_user="root" date="2017-07-11" exe="/usr/sbin/useradd" node="zabbix" op="adding" pid="20885" res="success" ses="1254" terminal="pts/1" time="14:53:06.055" timezone="+0300" types="ADD_USER" uid="0" uid_user="root"
`
After that I create a new user (test3) and the information about the second user (test2) appears in audisp-simplify, but the information about the thirsd user (test3) is now absent.

**Comment by mtkirby** [comment]
Greetings.
Audisp-simplify is not real-time.  Due to the nature of auditd, it may take
1 to 4 lines to represent one single event.  Audisp-simplify will wait
until the next event occurs before printing the previous event in order to
ensure all possible lines in that prior event are received.  If useradd is
the only event you have in your audit rules, you will always only see the
prior event.  Audisp-simplify is designed to monitor execve events, which
are common, thus reporting events quite often.

**Comment by meshkov** [comment]
Thank you for your answer.
